POST http://127.0.0.1:54321/functions/v1/stock_price
Content-Type: application/json

{
  "symbol": "samsung"
}

###

POST https://esawdtpiauocuvyjziif.supabase.co/functions/v1/stock_price
Content-Type: application/json

{
  "symbol": "twitter"
}

###

